### ISSUE TITLE
Configuring keys is impossible

### ISSUE THREAD

**Issue by danielmmmm** [kaaass/Kero-Blaster-vita#2]
Awesome to see this game on the Vita, thanks :-)

Since we have only a few "keys" available, the only way to re-assign a new key layout is to temporarily have one or more keys assigned twice. E.g. to switch the jump and shoot keys. Kero doesn't like this and complains: "Cannot set to the same key"

Even when I try to "override" the exact same keys as the default configuration, the game will often end the key configuration saying "Cannot set to the same key".

Using the touchscreen doesn't work either, since I can't tap any of the screen elements (the button functions or the keyboard on the bottom of the screen).

Is there a way to set the keys in user.keyconfig? I can't figure out what the string (hex?) in user.keyconfig does.

----------

**One thing I noticed:** There seems to be something weird going on with key polling. Could it be polling too fast and thereby registering a single press as two consecutive presses? Or are the keypresses not debounced in software?

I actually managed to remap the keys. Whenever Kero complains ("Cannot set to the same key"), I wait 5 to 10 seconds to try again. Eventually, I made it all the way to the end 😁

**Comment by kaaass** [comment]
Thank you for testing and reporting!

Yes, the control key configuration is a little bit annoying. And unfortunately, this problem also exists in the original Android game and could be triggered by keyboard input, so fixing it in this port is very challenging. Maybe I'll add a extra GUI menu to handle the config.

> Is there a way to set the keys in `user.keyconfig` ?

Yes, but tough. `user.keyconfig` is a binary file with 8 bytes header and 14 bytes key config bytes array (only first 9 bytes make sense, value could refer to [here](https://github.com/kaaass/Kero-Blaster-vita/blob/master/loader/control.c#L17-L50)).

**Comment by alula** [comment]
Kero Blaster 1.6.1 fixed this particular key configuration menu bug and has a native gamepad support on Android. 
I suggest updating the supported game version in your port :)

**Comment by kaaass** [comment]
@alula Thanks for reminding me that! Unfortunately, as I checked the 1.6.1 files, it seems the author had done a minor rewrite of several APIs. I tried to do a quick adaption, but it resulted in a buggy game (it seems several files such as `words.txt` have not been loaded properly). Since the 1.6.0 version port had already achieved a nearly perfect state (only key configuration and game exit have issues so far), I may not have enough willingness to debug for those bugs presented in 1.6.1. I might give it another try later when I'm available.

**Comment by alula** [comment]
> (it seems several files such as words.txt have not been loaded properly)

That sounds like you somehow messed up your implementation of `AAsset_*` functions.

Anyways, if you want to stick to 1.6.0 and want to fix the key config menu bug you'd have to relocate the call to `sub_167E4` to ensure it runs before each iteration of the loop at 0x17EFE.  And since it's a bit tricky to do I just suggest to update to 1.6.1 :)

**Comment by kaaass** [comment]
> That sounds like you somehow messed up your implementation of `AAsset_*` functions.

Ah yes, I just noticed I had made a silly mistake in the implementation of `AAsset_getLength`. Now everything works fine. Thanks for your advice!

**Comment by kaaass** [comment]
This bug is fixed in v1.1.

**Comment by danielmmmm** [comment]
Thanks a lot for the update! 😊
